### ISSUE TITLE
Fill Nodes doesn't consider speed settings from start and endpoint

### ISSUE THREAD

**Issue by AndyK70** [PromGames/Coursedrawer#11]
Sorry I'm waltzing in here, without invitation.
I've read your post over at courseplay and was too curious not to get a copy of that beta.
Just after "a couple of minutes" I realized I'm fiddeling around and editing/optimizing my routes with this for over 2 hours now and I got to go to bed...
But wanted to leave at least one experience:

When I have created a new line, set speed to 40 at first node and speed to 40 at second node I would expect that all nodes filled in will have the same speed setting of 40.

If 1st is set to 40 and 2nd is set to 10, well that's going to be a little complicated.
The easiest way would be interpolate from the first to the last.
A bit more sophisticated would be having only the last nodes brake down to 10. As straight lines a most common for same speed and only at the end of a straight line we're going to expect a turn if the speed is much lower than at the beginning.

Great tool btw.
Loving it!!

**Comment by PromGames** [comment]
Thank you for your feedback.

**Comment by Madbros** [comment]
Can be we can put some options to fill nodes:

- same speed as first node (as now)
-same speed as last node
-extrapolate (not interpolate!) speeds between first and last node.
-Brake or Accelerate on last x nodes (that is, extrapolate only in this last nodes)

**Comment by AndyK70** [comment]
closed... because already integrated as Madbros said?

**Comment by AndyK70** [comment]
just to be nerd :tongue: 
@Madbros interpolate is right, because those speeds are inside a defined range, you extrapolate if you are calculating values outside of your range.
