### ISSUE TITLE
Dragging the map is stuttering

### ISSUE THREAD

**Issue by AndyK70** [PromGames/Coursedrawer#12]
More courses shown more stuttering occurs.

Maybe you could render the map only while dragging and after releasing the mouse/slider draw the selected courses once.
That way the dragging would be fast and fluid.

**Comment by PromGames** [comment]
Unfortunately we couldn't upgrade the ***old*** draw module used by the original author.

 If you just select few courses, the program will go easy. 
We just label it as a possible enhancement for future release.
Thank you for feedback

**Comment by Madbros** [comment]
Courses are rendered in the picture from the begining, when we drag the map we are only dragging the picture, there are not course redrawing. No way to improve this, it is microsoft.

**Comment by AndyK70** [comment]
@PromGames it happens to me even with only one course visible. Not very much, but noticable.

I don't have a hyper rack, but think it is not too bad:
AMD FX6300 (6x 4GHz)
8GB RAM
AMD R9 270X
256GB SSD (System)
2TB HDD (Data)

Do you use BitBlit, DirectDraw 2D or DirectX to render?

@Madbros 
Don't mind, if I peek a little deeper?
Rendering the map area isn't at least a two step procedure? First the picture of the map and then on top the lines for the courses? *Didn't peek into your code yet, so don't blame me for not using your object/variable naming shema.*
Would imagine that you could postpone the rendering of the courses with just an 
´´´
if Mouse.isPressed == false {
  // rendering of courses occurs here
}
´´´

**Comment by Madbros** [comment]
as far as can see in this code, courses are drawed directly into bitmap, no way to redraw it without deleting and recreating te bitmap itself!

**Comment by Madbros** [comment]
the question is ¿why is this more stuttering if more courses, if only a bitmap? lets see system.graphics, can be i am wrong
