### ISSUE TITLE
deleting a node => no node selected

### ISSUE THREAD

**Issue by AndyK70** [PromGames/Coursedrawer#14]
As to say, if there are 100 nodes an I have node 76 selected and delete it, then old node 77 becomes node 76. It would be nice if that new node number 76 would be selected.

That way I could delete a couple of nodes one node after another without picking each one with the mouse.

**Comment by PromGames** [comment]
What you say is what is happening in fact. But is selected 78.

In conclusion 
You want us to be able to choose in the program the direction you want to delete, insert or Create next point. To + or to -

**Comment by AndyK70** [comment]
Well...
I didn't know that a node was selected after I deleted one, because of the missing white color. :wink: 
For me it would be enough to have the visual feedback some node was being selected.
Which direction is not important, when you know which direction the program will delete you start accordingly.

Don't know if it would be so easy to implement that option you named. For now I wouldn't consider that option urgend, but the white marking for the selected node.

**Comment by AndyK70** [comment]
wontfix ... Meaning that the white marker won't be set for the selected node?

**Comment by Madbros** [comment]
done in this release
