### ISSUE TITLE
Selecting a couple of nodes

### ISSUE THREAD

**Issue by AndyK70** [PromGames/Coursedrawer#15]
If I have a range of nodes I want to move as group, or want to delete them as whole (but not the whole track), it would be very handy to be able to select not just one node.

maybe like in painting programs?
selecting in form of a rectangle and or free shape.

support of modifiers:
- holding down shift adds the new selected nodes to the already selected ones.
- holding ctrl removes the selected nodes from the selected ones.
- holding Alt does it XOR-like.

**Comment by PromGames** [comment]
This was already in our pipeline. But using keyboard short-cuts will make easier to deal with it. Thanks Andy

**Comment by AndyK70** [comment]
closed... already implemented?
