### ISSUE TITLE
waypoint attribute "angle" set to "0.00" by inserting new WP

### ISSUE THREAD

**Issue by MPSBandit** [PromGames/Coursedrawer#18]
i inserted two new waypoints (WP 3+4). the attribute "angle" is set to "0.00"
im not sure what this value represents/indicates and what it should be. maybe there is a way to calculate this value?

edit: i used CD .006

```xml
<course name="20 abfahr 2" id="8" parent="0">
      <waypoint1 pos="186.60 -520.46" angle="-93.60" crossing="1" speed="0" />
      <waypoint2 pos="176.53 -521.10" angle="-69.18" speed="22" />
      <waypoint3 pos="166.75 -520.75" angle="0.00" speed="23" />
      <waypoint4 pos="161.00 -518.75" angle="0.00" speed="23" />
      <waypoint5 pos="157.79 -513.97" angle="-6.01" speed="23" />
      <waypoint6 pos="157.26 -508.85" angle="-2.42" speed="27" />
```

before
![before](https://cloud.githubusercontent.com/assets/10454932/5748274/f7ee117e-9c3e-11e4-9964-e1102a550e1d.PNG)

after
![after](https://cloud.githubusercontent.com/assets/10454932/5748276/feb330ac-9c3e-11e4-9cf3-efe782624ec1.PNG)

**Comment by gui7545** [comment]
Did you try the recalculation button ?
![capture](https://cloud.githubusercontent.com/assets/2854643/5748524/e6b10a0e-9c40-11e4-982e-4d3110b3352a.JPG)
You have to use it eachtime you modify a course (add point, move point ....)

**Comment by MPSBandit** [comment]
Fuck. my bad!
rtfm...

Have i to use it at each waypoint or each course i modified?
As i tried it right now the first time nothing happens (i selected the course). After the 3rd try it worked (maybe i waited too short)

Thx

**Comment by PromGames** [comment]
You may use the calculation button as said by @gui7545 

![capture](https://cloud.githubusercontent.com/assets/2854643/5748524/e6b10a0e-9c40-11e4-982e-4d3110b3352a.JPG)

All angles are calculated correctly with this function but there is one Warning:
If your route have way points with reverse attribute, you will get incorrect angle values in those specific Reverse-WP's

**Comment by MPSBandit** [comment]
thanks for explanation. that is why it worked after the first time.
