### ISSUE TITLE
add the FS2015 maps images to the github

### ISSUE THREAD

**Issue by Goten87** [PromGames/Coursedrawer#4]
heey can you add the maps images to the project or link them in the info section for people who dont know how to convert it

**Comment by PromGames** [comment]
I think the best way is to use the free tool paint.net.
Then it will convert you the pdamap to bmp.
Be sure you use the correct size of the map when saving to BMP.

Which map do you need the file?

**Comment by Goten87** [comment]
Both of them please becose i play them both

**Comment by Goten87** [comment]
i found somthing online :P that do what i need it to do http://image.online-convert.com/convert-to-bmp
so i now have my maps converted

**Comment by Madbros** [comment]
http://www.getpaint.net/

**Comment by Madbros** [comment]
standard maps uploaded
