### ISSUE TITLE
Accuracy of the pointer cursor

### ISSUE THREAD

**Issue by PromGames** [PromGames/Coursedrawer#8]
When using the arrow pointer in the screen with max zoom the accuracy to select a point is not exact. Has some deviation. We may check it in big maps and in standard maps to see if works better in the small ones

**Comment by PromGames** [comment]
When pointing the screen, there is  a parmeter which controls the accuracy of the pointer. It is set to 3 ¿pixels?. Selecting the closest point to that range. 

***Sugestion***
Include a button field with this value allowing the user to change the range where to apply the pointer

**Comment by Madbros** [comment]
I agree, can be in the future 'settings' feature.
