### ISSUE TITLE
Coursedrawer Window

### ISSUE THREAD

**Issue by MPSBandit** [PromGames/Coursedrawer#9]
If i start Coursedrawer i can't see all fields completely. I'm not sure if this is a issue of mine or of the Application. I can't change the size of the sidepanel as well. The overall windowsize is adjustable.
![coursedrawer](https://cloud.githubusercontent.com/assets/10454932/5680495/3e0be666-980e-11e4-8d68-8d878c5ff990.png)

**Comment by Madbros** [comment]
By me it works well, all panel data visible, adjusting only the map picture when resizing the window.
Sidepanel size is not adjustable. 

Can you tell us what OS and screen resolution are you using?

**Comment by MPSBandit** [comment]
Sure. Win 7 64Bit 1280*1024. As you mention the resolution: On my Win 7 64Bit Laptop with 1366*768 i can see everything fine.

Thanks
